src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 180)]
    #[Assert\Email(message: "Le format du courriel n'est pas valide")]
    #[Assert\NotBlank(message: "Le courriel est obligatoire")]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le Nom est obligatoire")]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le Prénom est obligatoire")]
    private ?string $firstname = null;

    #[ORM\OneToOne(inversedBy: 'owner', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'parcelle_id',referencedColumnName:'id',nullable:true,onDelete:'SET NULL')]
    private ?Parcelle $parcelle = null;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $posts;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $comments;

    /**
     * @var Collection<int, InscriptionReunion>
     */
    #[ORM\OneToMany(targetEntity: InscriptionReunion::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $inscriptionReunions;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $token = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isVerified = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastConnection = null;

    #[ORM\Column]
    private bool $isActive = true;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $desactivateAt = null;


    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->inscriptionReunions = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getFullname();
    }

    public function getFullname(): string
    {
        if ($this->isActive()) {
            return $this->getFirstname() . ' ' . $this->getLastname();
        } else {
            return 'Utilisateur suspendu';
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getParcelle(): ?Parcelle
    {
        return $this->parcelle;
    }

    public function setParcelle(?Parcelle $parcelle): static
    {
        $this->parcelle = $parcelle;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, InscriptionReunion>
     */
    public function getInscriptionReunions(): Collection
    {
        return $this->inscriptionReunions;
    }

    public function addInscriptionReunion(InscriptionReunion $inscriptionReunion): static
    {
        if (!$this->inscriptionReunions->contains($inscriptionReunion)) {
            $this->inscriptionReunions->add($inscriptionReunion);
            $inscriptionReunion->setUser($this);
        }

        return $this;
    }

    public function removeInscriptionReunion(InscriptionReunion $inscriptionReunion): static
    {
        if ($this->inscriptionReunions->removeElement($inscriptionReunion)) {
            // set the owning side to null (unless already changed)
            if ($inscriptionReunion->getUser() === $this) {
                $inscriptionReunion->setUser(null);
            }
        }

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function isVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(?bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getLastConnection(): ?\DateTimeInterface
    {
        return $this->lastConnection;
    }

    public function setLastConnection(?\DateTimeInterface $lastConnection): static
    {
        $this->lastConnection = $lastConnection;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): static
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getDesactivateAt(): ?\DateTimeImmutable
    {
        return $this->desactivateAt;
    }

    public function setDesactivateAt(?\DateTimeImmutable $desactivateAt): static
    {
        $this->desactivateAt = $desactivateAt;

        return $this;
    }
}

src/Controller/Admin/AdminCommentController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/comment')]
final class AdminCommentController extends AbstractController{
    #[Route(name: 'app_admin_comment_index', methods: ['GET'])]
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('admin_comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_comment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_comment_index', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->render('admin_comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_comment_show', methods: ['GET'])]
    public function show(Comment $comment): Response
    {
        return $this->render('admin_comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_comment_delete', methods: ['POST'])]
    public function delete(Request $request, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_comment/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer ce commentaire?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/admin_comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier commentaire
{% endblock %}

{% block body %}
	<h1>Modifier commentaire</h1>

	{{ include('admin_comment/_form.html.twig', {'button_label': 'Modifier'}) }}

	<div class="d-flex flex-column align-items-start gap-2 mt-2">
		{{ include('admin_comment/_delete_form.html.twig') }}
		<a href="{{ path('app_admin_comment_index') }}" class="btn btn-secondary">Retour</a>
	</div>
{% endblock %}

templates/admin_comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Commentaires
{% endblock %}

{% block body %}
	<h1>Liste des Commentaires</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Auteur</th>
				<th>Message</th>
				<th>Créé le</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for comment in comments %}
				<tr>
					<td>{{ comment.id }}</td>
					<td>{{ comment.user.fullname }}</td>
					<td>{{ comment.message|u.truncate(30, '...', false) }}</td>
					<td>{{ comment.createdAt ? comment.createdAt|date('d/m/Y H:i') : '' }}</td>
					<td>
						<a href="{{ path('app_admin_comment_show', {'id': comment.id}) }}" class="btn btn-secondary">Afficher</a>
						<a href="{{ path('app_admin_comment_edit', {'id': comment.id}) }}" class="btn btn-primary">Modifier</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="4">Pas de commentaire trouvé</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_admin_comment_new') }}" class="btn btn-success">Nouveau</a>
{% endblock %}

templates/admin_comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau commentaire{% endblock %}

{% block body %}
    <h1>Créer un nouveau commentaire</h1>

    {{ include('admin_comment/_form.html.twig') }}

    <a href="{{ path('app_admin_comment_index') }}" class="btn btn-secondary mt-2">Retour</a>
{% endblock %}

templates/admin_comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire
{% endblock %}

{% block body %}
	<h1>Commentaire</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Message</th>
				<td>
					{{ comment.message }}
					<p>Nombre de caractères :
						{{ comment.getLenghtMessage}}</p>
				</td>

			</tr>
			<tr>
				<th>Créé le</th>
				<td>{{ comment.createdAt ? comment.createdAt|date('d/m/Y H:i') : '' }}</td>
			</tr>
			<tr>
				<th>Du Post</th>
				{# Récupération de l'id du post  #}
				<td>
					<a href="{{ path("app_admin_post_show", {id:comment.post.id }) }}" class="text-primary" target="_blank">Voir le Post</a>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="d-flex flex-column align-items-start gap-2">
		<a href="{{ path('app_admin_comment_edit', {'id': comment.id}) }}" class="btn btn-primary">Modifier</a>

		{{ include('admin_comment/_delete_form.html.twig') }}

		<a href="{{ path('app_admin_comment_index') }}" class="btn btn-secondary">Retour</a>
	</div>
{% endblock %}